/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.domain.jooq;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.tinkoff.edu.domain.jooq.tables.Chat;
import ru.tinkoff.edu.domain.jooq.tables.Databasechangeloglock;
import ru.tinkoff.edu.domain.jooq.tables.Link;
import ru.tinkoff.edu.domain.jooq.tables.LinkChat;
import ru.tinkoff.edu.domain.jooq.tables.records.ChatRecord;
import ru.tinkoff.edu.domain.jooq.tables.records.DatabasechangeloglockRecord;
import ru.tinkoff.edu.domain.jooq.tables.records.LinkChatRecord;
import ru.tinkoff.edu.domain.jooq.tables.records.LinkRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CHAT_PKEY = Internal.createUniqueKey(Chat.CHAT, DSL.name("chat_pkey"), new TableField[] { Chat.CHAT.ID }, true);
    public static final UniqueKey<DatabasechangeloglockRecord> DATABASECHANGELOGLOCK_PKEY = Internal.createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, DSL.name("databasechangeloglock_pkey"), new TableField[] { Databasechangeloglock.DATABASECHANGELOGLOCK.ID }, true);
    public static final UniqueKey<LinkRecord> LINK_PKEY = Internal.createUniqueKey(Link.LINK, DSL.name("link_pkey"), new TableField[] { Link.LINK.ID }, true);
    public static final UniqueKey<LinkRecord> LINK_URL_KEY = Internal.createUniqueKey(Link.LINK, DSL.name("link_url_key"), new TableField[] { Link.LINK.URL }, true);
    public static final UniqueKey<LinkChatRecord> LINK_CHAT_PKEY = Internal.createUniqueKey(LinkChat.LINK_CHAT, DSL.name("link_chat_pkey"), new TableField[] { LinkChat.LINK_CHAT.CHAT_ID, LinkChat.LINK_CHAT.LINK_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<LinkChatRecord, ChatRecord> LINK_CHAT__LINK_CHAT_CHAT_ID_FKEY = Internal.createForeignKey(LinkChat.LINK_CHAT, DSL.name("link_chat_chat_id_fkey"), new TableField[] { LinkChat.LINK_CHAT.CHAT_ID }, Keys.CHAT_PKEY, new TableField[] { Chat.CHAT.ID }, true);
    public static final ForeignKey<LinkChatRecord, LinkRecord> LINK_CHAT__LINK_CHAT_LINK_ID_FKEY = Internal.createForeignKey(LinkChat.LINK_CHAT, DSL.name("link_chat_link_id_fkey"), new TableField[] { LinkChat.LINK_CHAT.LINK_ID }, Keys.LINK_PKEY, new TableField[] { Link.LINK.ID }, true);
}
