/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.domain.jooq;


import ru.tinkoff.edu.domain.jooq.tables.Chat;
import ru.tinkoff.edu.domain.jooq.tables.Databasechangelog;
import ru.tinkoff.edu.domain.jooq.tables.Databasechangeloglock;
import ru.tinkoff.edu.domain.jooq.tables.Link;
import ru.tinkoff.edu.domain.jooq.tables.LinkChat;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.chat</code>.
     */
    public static final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.link</code>.
     */
    public static final Link LINK = Link.LINK;

    /**
     * The table <code>public.link_chat</code>.
     */
    public static final LinkChat LINK_CHAT = LinkChat.LINK_CHAT;
}
