/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.domain.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tinkoff.edu.domain.jooq.tables.Link;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinkRecord extends UpdatableRecordImpl<LinkRecord> implements Record5<Integer, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.link.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.link.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.link.url</code>.
     */
    public void setUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.link.url</code>.
     */
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.link.linkname</code>.
     */
    public void setLinkname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.link.linkname</code>.
     */
    public String getLinkname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.link.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.link.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.link.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.link.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Link.LINK.ID;
    }

    @Override
    public Field<String> field2() {
        return Link.LINK.URL;
    }

    @Override
    public Field<String> field3() {
        return Link.LINK.LINKNAME;
    }

    @Override
    public Field<String> field4() {
        return Link.LINK.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Link.LINK.UPDATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUrl();
    }

    @Override
    public String component3() {
        return getLinkname();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUrl();
    }

    @Override
    public String value3() {
        return getLinkname();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdatedAt();
    }

    @Override
    public LinkRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public LinkRecord value2(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public LinkRecord value3(String value) {
        setLinkname(value);
        return this;
    }

    @Override
    public LinkRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public LinkRecord value5(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public LinkRecord values(Integer value1, String value2, String value3, String value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinkRecord
     */
    public LinkRecord() {
        super(Link.LINK);
    }

    /**
     * Create a detached, initialised LinkRecord
     */
    public LinkRecord(Integer id, String url, String linkname, String description, LocalDateTime updatedAt) {
        super(Link.LINK);

        setId(id);
        setUrl(url);
        setLinkname(linkname);
        setDescription(description);
        setUpdatedAt(updatedAt);
    }
}
