/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.domain.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tinkoff.edu.domain.jooq.tables.LinkChat;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinkChatRecord extends UpdatableRecordImpl<LinkChatRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.link_chat.chat_id</code>.
     */
    public void setChatId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.link_chat.chat_id</code>.
     */
    public Integer getChatId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.link_chat.link_id</code>.
     */
    public void setLinkId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.link_chat.link_id</code>.
     */
    public Integer getLinkId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return LinkChat.LINK_CHAT.CHAT_ID;
    }

    @Override
    public Field<Integer> field2() {
        return LinkChat.LINK_CHAT.LINK_ID;
    }

    @Override
    public Integer component1() {
        return getChatId();
    }

    @Override
    public Integer component2() {
        return getLinkId();
    }

    @Override
    public Integer value1() {
        return getChatId();
    }

    @Override
    public Integer value2() {
        return getLinkId();
    }

    @Override
    public LinkChatRecord value1(Integer value) {
        setChatId(value);
        return this;
    }

    @Override
    public LinkChatRecord value2(Integer value) {
        setLinkId(value);
        return this;
    }

    @Override
    public LinkChatRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinkChatRecord
     */
    public LinkChatRecord() {
        super(LinkChat.LINK_CHAT);
    }

    /**
     * Create a detached, initialised LinkChatRecord
     */
    public LinkChatRecord(Integer chatId, Integer linkId) {
        super(LinkChat.LINK_CHAT);

        setChatId(chatId);
        setLinkId(linkId);
    }
}
